# Generated by Django 3.2.13 on 2023-01-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('published_datetime', models.DateTimeField(auto_now_add=True)),
                ('boby', models.CharField(max_length=500)),
                ('attachment_list', models.CharField(max_length=500)),
            ],
        ),
    ]
